table _Measures
	isHidden
	lineageTag: 70d50eba-454f-5579-8105-aeff160c829f

	/// Total gold value of all trades.
	measure 'Total Trade Value' = SUM(FactTrade[TotalPrice])
		formatString: $#,##0
		displayFolder: 1. Headline
		lineageTag: 84354dc0-0473-5749-baf7-03ef50c7469d

	/// Total units traded across all trades.
	measure 'Trade Quantity' = SUM(FactTrade[Quantity])
		formatString: #,##0
		displayFolder: 1. Headline
		lineageTag: ed42dd02-78db-536e-b358-a22e5b19c91f

	/// Number of trade transactions.
	measure 'Trade Count' = COUNTROWS(FactTrade)
		formatString: #,##0
		displayFolder: 1. Headline
		lineageTag: 1ef20e69-0237-548f-8bd0-9fb5d2148c0a

	/// Distinct tradeable items that changed hands.
	measure 'Distinct Items Traded' = DISTINCTCOUNT(FactTrade[ItemKey])
		formatString: #,##0
		displayFolder: 1. Headline
		lineageTag: a1e818fd-09b3-5ad5-86b1-2a6a17d1cc21

	/// Average daily market price across items in context.
	measure 'Avg Market Price' = AVERAGE(FactMarketPriceDaily[AvgPrice])
		formatString: $#,##0.00
		displayFolder: 2. Market
		lineageTag: cca897cd-37b9-5579-94fe-47d7f3d15c61

	/// Total units listed on the market (daily snapshot sum).
	measure 'Total Market Volume' = SUM(FactMarketPriceDaily[Volume])
		formatString: #,##0
		displayFolder: 2. Market
		lineageTag: 0fb54e06-8889-56db-b8ad-68b367501196

	/// Active listings on the market (daily snapshot sum).
	measure 'Active Listings' = SUM(FactMarketPriceDaily[ListingsCount])
		formatString: #,##0
		displayFolder: 2. Market
		lineageTag: 4b4b8914-79e2-5385-99e9-a43887121916

	/// Trade value year-to-date (needs the marked DimDate date table).
	measure 'Trade Value YTD' =
			CALCULATE(
				[Total Trade Value],
				DATESYTD(DimDate[Date])
			)
		formatString: $#,##0
		displayFolder: 3. Time Intelligence
		lineageTag: 6546e9aa-6dad-55c5-b8fc-c88f6aaf3a4f

	/// Trade value in the same period one year ago.
	measure 'Trade Value PY' =
			CALCULATE(
				[Total Trade Value],
				SAMEPERIODLASTYEAR(DimDate[Date])
			)
		formatString: $#,##0
		displayFolder: 3. Time Intelligence
		lineageTag: 89054b35-eef5-56b1-98e5-897876d00bc2

	measure 'Market Board SVG' = ```
			
			VAR _N = 12
			VAR _Items =
			    ADDCOLUMNS (
			        SUMMARIZE (
			            ALLSELECTED ( DimItem ),
			            DimItem[ItemKey], DimItem[ItemName], DimItem[RarityKey]
			        ),
			        "@price", [Avg Market Price],
			        "@listings", [Active Listings],
			        "@value", [Total Trade Value]
			    )
			VAR _Top = TOPN ( _N, FILTER ( _Items, [@value] > 0 ), [@value], DESC )
			VAR _MaxVal = MAXX ( _Top, [@value] )
			VAR _Rows =
			    CONCATENATEX (
			        _Top,
			        VAR _name  = SUBSTITUTE ( DimItem[ItemName], "&", "&amp;" )
			        VAR _col   = LOOKUPVALUE ( DimRarity[ColorHex], DimRarity[RarityKey], DimItem[RarityKey] )
			        VAR _price = FORMAT ( [@price], "#,##0" )
			        VAR _qty   = FORMAT ( [@listings], "#,##0" )
			        VAR _pct   = INT ( DIVIDE ( [@value], _MaxVal ) * 100 )
			        RETURN
			            "<div class='r'>" &
			                "<div class='nm' style='border-left:3px solid " & _col & ";color:" & _col & "'>" & _name & "</div>" &
			                "<div class='pr'>" & _price & "<span class='u'> gp</span></div>" &
			                "<div class='qty'>" & _qty & "</div>" &
			                "<div class='bar'><span style='width:" & _pct & "%'></span></div>" &
			            "</div>",
			        ""
			    )
			RETURN
			    "data:image/svg+xml;utf8," &
			    "<svg xmlns='http://www.w3.org/2000/svg' width='620' height='460'>" &
			    "<foreignObject x='0' y='0' width='620' height='460'>" &
			    "<div xmlns='http://www.w3.org/1999/xhtml' class='ge'>" &
			    "<style>" &
			    ".ge{width:620px;height:460px;box-sizing:border-box;font-family:Segoe UI,Arial,sans-serif;background:linear-gradient(180deg,#1b2436,#101726);border:2px solid #c9a227;border-radius:12px;padding:14px 16px;color:#e8edf5}" &
			    ".ge .hd{display:flex;align-items:baseline;justify-content:space-between;border-bottom:1px solid #2c3a52;padding-bottom:8px;margin-bottom:2px}" &
			    ".ge .ttl{font-size:18px;font-weight:700;letter-spacing:2px;color:#e8c349}" &
			    ".ge .sub{font-size:11px;color:#8aa0c0;text-transform:uppercase;letter-spacing:1px}" &
			    ".ge .ch,.ge .r{display:grid;grid-template-columns:1fr 110px 70px 90px;align-items:center;column-gap:10px}" &
			    ".ge .ch{font-size:10px;color:#7d92b3;text-transform:uppercase;letter-spacing:1px;padding:6px 0 4px;border-bottom:1px solid #2c3a52}" &
			    ".ge .ch .ra{text-align:right}" &
			    ".ge .r{padding:5px 0;border-bottom:1px solid #1b243a;font-size:13px}" &
			    ".ge .nm{padding-left:8px;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}" &
			    ".ge .pr{text-align:right;font-weight:600;color:#f4d770;font-variant-numeric:tabular-nums}" &
			    ".ge .pr .u{color:#9a8a3f;font-weight:400;font-size:11px}" &
			    ".ge .qty{text-align:right;color:#9fb3d1;font-variant-numeric:tabular-nums}" &
			    ".ge .bar{height:7px;background:#1f2a3d;border-radius:4px;overflow:hidden}" &
			    ".ge .bar span{display:block;height:100%;background:linear-gradient(90deg,#c9a227,#f4d770)}" &
			    "</style>" &
			    "<div class='hd'><div class='ttl'>THE GRAND EXCHANGE</div><div class='sub'>Live Market Board</div></div>" &
			    "<div class='ch'><div>Item</div><div class='ra'>Unit Price</div><div class='ra'>Listings</div><div class='ra'>Value</div></div>" &
			    _Rows &
			    "</div></foreignObject></svg>"
			
			```
		lineageTag: 72df6be0-2304-4d24-bb0f-5687582fb9d7
		dataCategory: ImageUrl

	measure 'Spinner SVG' = ```
			
			"data:image/svg+xml;utf8," &
			"<svg xmlns='http://www.w3.org/2000/svg' width='48' height='48'>" &
			  "<g fill='none' stroke='#c9a227' stroke-width='5' stroke-linecap='round'>" &
			    "<circle cx='24' cy='24' r='18' stroke='#2c3a52'/>" &
			    "<path d='M24 6 a18 18 0 0 1 18 18'>" &
			      "<animateTransform attributeName='transform' type='rotate' from='0 24 24' to='360 24 24' dur='0.9s' repeatCount='indefinite'/>" &
			    "</path>" &
			  "</g>" &
			"</svg>"
			
			```
		lineageTag: 1a29b170-1cc8-4c91-8da3-59f4803202a8
		dataCategory: ImageUrl

	column _
		lineageTag: 271a7b31-cdcd-5410-81c4-6ed8fb705b55
		isNameInferred
		sourceColumn: [_]

	partition _Measures = calculated
		mode: import
		source = ROW("_", "")

	annotation PBI_ResultType = Table

