table _Measures
	isHidden
	lineageTag: cfff4bff-9707-4543-823b-798f2f9200bb

	/// Sum of Sales across the financials table.
	measure 'Total Sales' = SUM(financials[Sales])
		formatString: $#,##0
		displayFolder: 1. Headline
		lineageTag: 329a1c8c-d06a-4161-8694-588fffbc8a84

	/// Sum of Units Sold across the financials table.
	measure 'Total Units' = SUM(financials[Units Sold])
		formatString: #,##0
		displayFolder: 1. Headline
		lineageTag: 2763e46d-4048-4c8f-aa88-730f6e22faaa

	/// Sum of Profit across the financials table.
	measure 'Total Profit' = SUM(financials[Profit])
		formatString: $#,##0
		displayFolder: 1. Headline
		lineageTag: 4383d50c-6c0b-474b-bffd-337e61a47d52

	/// Sum of COGS across the financials table.
	measure 'Total COGS' = SUM(financials[COGS])
		formatString: $#,##0
		displayFolder: 1. Headline
		lineageTag: 29be152a-5bd6-427a-ac18-d6b0952d5b85

	/// Profit as a percentage of Sales.
	measure 'Profit %' = DIVIDE([Total Profit], [Total Sales])
		formatString: 0.0%
		displayFolder: 2. Ratios
		lineageTag: b00e078f-3337-4a76-8eac-9d2350a4624f

	/// Discounts as a percentage of Gross Sales.
	measure 'Discount %' = DIVIDE(SUM(financials[Discounts]), SUM(financials[Gross Sales]))
		formatString: 0.0%
		displayFolder: 2. Ratios
		lineageTag: 49a8d1c0-47cb-4428-80d7-67beae925367

	/// Total Sales in the same period one year ago.
	measure 'Sales PY' =
			CALCULATE(
				[Total Sales],
				SAMEPERIODLASTYEAR(financials[Date])
			)
		formatString: $#,##0
		displayFolder: 3. Time Intelligence
		lineageTag: 5ba9147d-9e4d-4545-97d7-a18545d63056

	/// Year-to-date Total Sales.
	measure 'Sales YTD' =
			CALCULATE(
				[Total Sales],
				DATESYTD(financials[Date])
			)
		formatString: $#,##0
		displayFolder: 3. Time Intelligence
		lineageTag: 9f89cf28-134e-4c1b-bc75-f16c22b0e8d4

	/// Average sale price across the financials table.
	measure 'Avg Sale Price' = AVERAGE(financials[Sale Price])
		formatString: $#,##0.00
		displayFolder: 4. Averages
		lineageTag: 18569ed5-6bb0-4626-976f-4c8b94f7ef36

	/// SVG progress bar visualizing Profit % (0-100%). Red < 10%, amber 10-20%, green >= 20%.
	measure 'Profit % SVG' =
			VAR _Pct = MIN( COALESCE( [Profit %], 0 ), 1 )
			VAR _W = 120
			VAR _H = 18
			VAR _FillW = _Pct * _W
			VAR _Color =
				SWITCH(
					TRUE(),
					_Pct < 0.10, "#E03131",
					_Pct < 0.20, "#F08C00",
					"#2F9E44"
				)
			VAR _Label = FORMAT( _Pct, "0.0%" )
			RETURN
				"data:image/svg+xml;utf8," &
				"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " & _W & " " & _H & "'>" &
				"<rect width='" & _W & "' height='" & _H & "' fill='#E9ECEF' rx='" & (_H / 2) & "'/>" &
				"<rect width='" & _FillW & "' height='" & _H & "' fill='" & _Color & "' rx='" & (_H / 2) & "'/>" &
				"<text x='" & (_W / 2) & "' y='" & (_H / 2 + 4) & "' font-size='11' text-anchor='middle' fill='#212529' font-family='Segoe UI'>" & _Label & "</text>" &
				"</svg>"
		displayFolder: 5. SVG
		lineageTag: a1f1c3e4-1111-4aaa-9bbb-111111111111
		dataCategory: ImageUrl

	/// SVG status pill: green for Profit > 0, red for loss, gray for zero.
	measure 'Profit Pill SVG' =
			VAR _Profit = [Total Profit]
			VAR _State =
				SWITCH(
					TRUE(),
					ISBLANK( _Profit ) || _Profit = 0, "#868E96",
					_Profit < 0, "#E03131",
					"#2F9E44"
				)
			VAR _Label =
				SWITCH(
					TRUE(),
					ISBLANK( _Profit ) || _Profit = 0, "—",
					_Profit < 0, "LOSS",
					"PROFIT"
				)
			VAR _W = 70
			VAR _H = 18
			RETURN
				"data:image/svg+xml;utf8," &
				"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " & _W & " " & _H & "'>" &
				"<rect width='" & _W & "' height='" & _H & "' fill='" & _State & "' rx='" & (_H / 2) & "'/>" &
				"<text x='" & (_W / 2) & "' y='" & (_H / 2 + 4) & "' font-size='10' text-anchor='middle' fill='#FFFFFF' font-family='Segoe UI' font-weight='bold'>" & _Label & "</text>" &
				"</svg>"
		displayFolder: 5. SVG
		lineageTag: a2f2c4e5-2222-4aaa-9bbb-222222222222
		dataCategory: ImageUrl

	/// GitHub-style SVG heatmap: small cells per year-month, colored by sales intensity (current row's product). Color scale is global across all product/month combos so cells are comparable across rows.
	measure 'Heatmap SVG' =
			VAR _CW = 14
			VAR _CH = 14
			VAR _G = 2
			VAR _DistinctYMs =
				DISTINCT(
					SELECTCOLUMNS(
						ALL( financials ),
						"YM", YEAR( financials[Date] ) * 100 + MONTH( financials[Date] )
					)
				)
			VAR _RankedMonths =
				ADDCOLUMNS(
					_DistinctYMs,
					"Idx",
						VAR _Cur = [YM]
						RETURN COUNTROWS( FILTER( _DistinctYMs, [YM] < _Cur ) )
				)
			VAR _AllProductMonths =
				ADDCOLUMNS(
					CROSSJOIN(
						DISTINCT( SELECTCOLUMNS( ALL( financials ), "P", financials[Product] ) ),
						_DistinctYMs
					),
					"S",
						CALCULATE(
							SUM( financials[Sales] ),
							FILTER( ALL( financials ),
								financials[Product] = [P] &&
								YEAR( financials[Date] ) * 100 + MONTH( financials[Date] ) = [YM]
							)
						)
				)
			VAR _MaxS = MAXX( _AllProductMonths, [S] )
			VAR _Cells =
				CONCATENATEX(
					_RankedMonths,
					VAR _ThisYM = [YM]
					VAR _ThisIdx = [Idx]
					VAR _Sales =
						CALCULATE(
							SUM( financials[Sales] ),
							FILTER( ALL( financials[Date] ),
								YEAR( financials[Date] ) * 100 + MONTH( financials[Date] ) = _ThisYM
							)
						)
					VAR _I = DIVIDE( _Sales, _MaxS )
					VAR _X = _ThisIdx * (_CW + _G)
					VAR _C =
						SWITCH( TRUE(),
							ISBLANK( _Sales ) || _Sales <= 0, "#EBEDF0",
							_I < 0.25, "#9BE9A8",
							_I < 0.50, "#40C463",
							_I < 0.75, "#30A14E",
							"#216E39"
						)
					RETURN
						"<rect x='" & _X & "' y='0' width='" & _CW & "' height='" & _CH & "' fill='" & _C & "' rx='2'/>",
					"",
					[YM], ASC
				)
			VAR _N = COUNTROWS( _RankedMonths )
			VAR _W = _N * (_CW + _G)
			RETURN
				"data:image/svg+xml;utf8," &
				"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " & _W & " " & _CH & "'>" &
				_Cells &
				"</svg>"
		displayFolder: 5. SVG
		lineageTag: a4f4c6e7-4444-4aaa-9bbb-444444444444
		dataCategory: ImageUrl

	/// SVG discount intensity bar (0-50%). Color ramps from teal (low) to red (high).
	measure 'Discount % SVG' =
			VAR _Pct = MIN( COALESCE( [Discount %], 0 ) / 0.5, 1 )
			VAR _W = 100
			VAR _H = 14
			VAR _FillW = _Pct * _W
			VAR _Color =
				SWITCH(
					TRUE(),
					_Pct < 0.33, "#0C8599",
					_Pct < 0.66, "#F08C00",
					"#E03131"
				)
			RETURN
				"data:image/svg+xml;utf8," &
				"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " & _W & " " & _H & "'>" &
				"<rect width='" & _W & "' height='" & _H & "' fill='#E9ECEF' rx='2'/>" &
				"<rect width='" & _FillW & "' height='" & _H & "' fill='" & _Color & "' rx='2'/>" &
				"</svg>"
		displayFolder: 5. SVG
		lineageTag: a3f3c5e6-3333-4aaa-9bbb-333333333333
		dataCategory: ImageUrl

	/// Recipe harvester — MIN of the disconnected slicer selection (window start).
	measure 'Window Start Date' = MIN( 'financials Date Slicer'[Date] )
		formatString: General Date
		displayFolder: 6. Time window
		lineageTag: 35e4d64f-484c-415b-8a3d-b4017e6eba2e

	/// Recipe harvester — MAX of the disconnected slicer selection (window end).
	measure 'Window End Date' = MAX( 'financials Date Slicer'[Date] )
		formatString: General Date
		displayFolder: 6. Time window
		lineageTag: 74573d34-c044-463d-a186-ea17678d59b4

	/// Numeric-band harvester — MIN of the disconnected Price Slicer selection.
	measure 'Price Low' = MIN( 'Price Slicer'[Sale Price] )
		formatString: 0
		displayFolder: 7. Numeric band
		lineageTag: 35e72da4-5b85-411b-b526-138db58a3bf0

	/// Numeric-band harvester — MAX of the disconnected Price Slicer selection.
	measure 'Price High' = MAX( 'Price Slicer'[Sale Price] )
		formatString: 0
		displayFolder: 7. Numeric band
		lineageTag: 196e582a-0cdb-4b79-ac9e-aa346be9e2cc

	/// Comparison-period harvester — the single selected year off the disconnected Year Slicer.
	measure 'Selected Year' = SELECTEDVALUE( 'Year Slicer'[Year] )
		formatString: 0
		displayFolder: 8. Comparison period
		lineageTag: 81e12058-2138-4391-9e11-0e43243ada34

	/// First date of the selected year (mapped onto the related financials date). VAR materializes the picked year to a scalar so the CALCULATE filter is a plain boolean (avoids the "PLACEHOLDER in table filter" error from referencing a measure directly).
	measure 'Year Start' =
			VAR _y = [Selected Year]
			RETURN CALCULATE ( MIN ( financials[Date] ), REMOVEFILTERS ( financials ), financials[Year] = _y )
		formatString: General Date
		displayFolder: 8. Comparison period
		lineageTag: 61d1d634-ff88-416c-954b-77bd3bd405d7

	/// Last date of the selected year (mapped onto the related financials date).
	measure 'Year End' =
			VAR _y = [Selected Year]
			RETURN CALCULATE ( MAX ( financials[Date] ), REMOVEFILTERS ( financials ), financials[Year] = _y )
		formatString: General Date
		displayFolder: 8. Comparison period
		lineageTag: 57ad3f18-5946-4d67-887a-e87e9071df40

	/// Category-spotlight color — accent for products in the disconnected selection (or when none picked), muted grey otherwise. Bind to dataPoint fill.
	measure 'Spotlight Color' =
			VAR _sel = VALUES ( 'Product Slicer'[Product] )
			RETURN
				IF (
					NOT ISFILTERED ( 'Product Slicer'[Product] )
						|| SELECTEDVALUE ( financials[Product] ) IN _sel,
					"#118DFF",
					"#C8C8C8"
				)
		displayFolder: 9. Spotlight
		lineageTag: e27e5f06-cd8c-4ecd-9218-c6414200c2b5

	/// Pareto cumulative % of Total Sales in descending-value order — model-measure form (model-measure-pareto variant). ALLSELECTED clears only the axis category so slicers/page filters still apply (unlike ALL, which would make the cumulative slicer-proof).
	measure 'Cumulative %' =
			VAR _cur = [Total Sales]
			VAR _grand = CALCULATE ( [Total Sales], ALLSELECTED ( financials[Product] ) )
			VAR _cum =
				CALCULATE (
					[Total Sales],
					FILTER ( ALLSELECTED ( financials[Product] ), CALCULATE ( [Total Sales] ) >= _cur )
				)
			RETURN DIVIDE ( _cum, _grand )
		formatString: 0%
		displayFolder: A. Pareto (model)
		lineageTag: 6844b488-bcb4-4a8a-b2f9-45a30f0b65a2

	/// Pareto vital-few line segment, extended to the FIRST bar that crosses 80% so it shares a point with the red segment → one continuous line that flips color (no gap). _prev = cumulative excluding the current product; if that was still <80%, this bar is the crossing point and stays green.
	measure 'Cumulative Green' =
			VAR _grand = CALCULATE ( [Total Sales], ALLSELECTED ( financials[Product] ) )
			VAR _prev = [Cumulative %] - DIVIDE ( [Total Sales], _grand )
			RETURN IF ( _prev < 0.8, [Cumulative %] )
		formatString: 0%
		displayFolder: A. Pareto (model)
		lineageTag: 21152bbc-44f5-42e0-a8cf-c82da8f9b9a2

	/// Pareto trivial-many line segment (cumulative > 80%).
	measure 'Cumulative Red' = IF ( [Cumulative %] > 0.8, [Cumulative %] )
		formatString: 0%
		displayFolder: A. Pareto (model)
		lineageTag: d6184840-f03e-4f65-a857-c46d4b8b4db1

	/// Pareto bar color — teal inside the 80% cumulative, red beyond. Bind to dataPoint fill (with a dataViewWildcard selector so it evaluates per bar).
	measure 'Pareto Bar Color' = IF ( [Cumulative %] <= 0.8, "#1E9790", "#ED4D55" )
		displayFolder: A. Pareto (model)
		lineageTag: ca620ab5-2ed4-4bc4-a12b-3ce82f0f342b

	/// How many products make up the first 80% of sales — the number a visual calc can't feed to a card. This is the deciding reason to choose the model-measure variant.
	measure '# Products to 80%' = COUNTROWS ( FILTER ( VALUES ( financials[Product] ), [Cumulative %] <= 0.8 ) ) + 1
		formatString: 0
		displayFolder: A. Pareto (model)
		lineageTag: 3123cc2a-f8d7-401d-b139-82202385d3c7

	/// Synthetic target for the actual-vs-target recipe demo — the MEDIAN monthly Total Sales (a flat benchmark, so ~half the months beat it / half miss → both green and red show). ALLSELECTED(financials) clears the axis (Month Name) filter while respecting the page filter; using ALLSELECTED on a single month column would leave the axis filter and make every target = that month's own sales (all green).
	measure 'Sales Target' = CALCULATE ( MEDIANX ( VALUES ( financials[MonthKey] ), [Total Sales] ), ALLSELECTED ( financials ) )
		displayFolder: B. Actual vs Target
		lineageTag: ea15b137-5ca5-46b2-a494-432cc49ca4df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Delta = [Total Sales] - [Sales Target]
		displayFolder: B. Actual vs Target
		lineageTag: ce0b8e52-1341-46c3-82de-2a9e590c86ec

	measure '% Delta' = DIVIDE ( [Delta], [Sales Target] )
		displayFolder: B. Actual vs Target
		lineageTag: 50fa132f-ed9f-4c78-ae01-fab5590aa148

		formatStringDefinition = "▲0%;▼0%;0%"

	measure 'MAX VALUE' = IF ( [Total Sales] > [Sales Target], [Total Sales], [Sales Target] )
		displayFolder: B. Actual vs Target
		lineageTag: d8d17d5b-89b2-4cd9-a052-49d4196112ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GREEN MAX' = IF ( [Delta] > 0, [MAX VALUE] )
		displayFolder: B. Actual vs Target
		lineageTag: 810fcb74-6737-448a-807f-3086279fb537

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RED MAX' = IF ( [Delta] < 0, [MAX VALUE] )
		displayFolder: B. Actual vs Target
		lineageTag: 3b90f251-acf8-4a7a-8580-95d9f7c59729

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Color' = SWITCH ( TRUE (), [Delta] > 0, "#1B7F4A", [Delta] < 0, "#B00020", BLANK () )
		displayFolder: B. Actual vs Target
		lineageTag: 5f043dec-ce5e-41c6-bb6e-113e377335b3

	measure 'Number Successful Months' = COUNTROWS ( FILTER ( VALUES ( financials[MonthKey] ), CALCULATE ( [Delta] ) > 0 ) )
		formatString: 0
		displayFolder: B. Actual vs Target
		lineageTag: 6c74f700-0693-4f12-9ebc-104d5506d896

	measure 'Best Month' =
			VAR _Months =
				ADDCOLUMNS (
					VALUES ( financials[MonthKey] ),
					"DeltaMonth", CALCULATE ( [Delta] ),
					"MonthKeyNum",
						VAR _m = VALUE ( LEFT ( financials[MonthKey], 2 ) )
						VAR _y = VALUE ( RIGHT ( financials[MonthKey], 4 ) )
						RETURN _y * 12 + _m
				)
			VAR _Top1 = TOPN ( 1, FILTER ( _Months, [DeltaMonth] > 0 ), [DeltaMonth], DESC, [MonthKeyNum], ASC )
			VAR _BestMY = MAXX ( _Top1, financials[MonthKey] )
			RETURN
				IF ( ISBLANK ( _BestMY ), BLANK (),
					VAR _m = VALUE ( LEFT ( _BestMY, 2 ) )
					VAR _y = VALUE ( RIGHT ( _BestMY, 4 ) )
					RETURN FORMAT ( DATE ( _y, _m, 1 ), "mmmm" ) )
		displayFolder: B. Actual vs Target
		lineageTag: ac2d54e5-30c5-4072-9423-28e4739946da

	measure 'Longest Winning Streak' =
			VAR _Months =
				ADDCOLUMNS (
					VALUES ( financials[MonthKey] ),
					"MonthKeyNum",
						VAR _m = VALUE ( LEFT ( financials[MonthKey], 2 ) )
						VAR _y = VALUE ( RIGHT ( financials[MonthKey], 4 ) )
						RETURN _y * 12 + _m,
					"IsWin", IF ( CALCULATE ( [Delta] ) > 0, 1, 0 )
				)
			VAR _Wins = FILTER ( _Months, [IsWin] = 1 )
			VAR _Grouped = ADDCOLUMNS ( _Wins, "Grp", [MonthKeyNum] - RANKX ( _Wins, [MonthKeyNum], , ASC, DENSE ) )
			VAR _Streaks = GROUPBY ( _Grouped, [Grp], "StreakLen", COUNTX ( CURRENTGROUP (), 1 ) )
			RETURN COALESCE ( MAXX ( _Streaks, [StreakLen] ), 0 )
		formatString: 0
		displayFolder: B. Actual vs Target
		lineageTag: ab5ac941-8316-4d4b-a4aa-1236c2c23930

	measure TAKEAWAY =
			VAR _Year   = SELECTEDVALUE ( financials[Year] )
			VAR _Wins   = [Number Successful Months]
			VAR _Best   = [Best Month]
			VAR _Streak = [Longest Winning Streak]
			RETURN
				"In " & _Year & ", we beat target in " & _Wins &
				" months, with the strongest overperformance in " & _Best &
				" and the longest winning streak of " & _Streak & " months."
		displayFolder: B. Actual vs Target
		lineageTag: eea6108f-4c3f-4bae-91f8-d10d1a385a98

	/// Flat per-product target for the SVG gallery — average Total Sales across products.
	measure 'Product Target' = AVERAGEX ( ALLSELECTED ( financials[Product] ), [Total Sales] )
		formatString: $#,##0
		displayFolder: 7. SVG gallery
		lineageTag: 6badf6b8-6846-428d-af0f-36d3efdb2787

	/// SVG sparkline — Total Sales monthly trend for the current product.
	measure 'Sales Sparkline SVG' =
			VAR _m = ADDCOLUMNS ( SUMMARIZE ( financials, financials[Year], financials[Month Number] ), "@idx", financials[Year] * 12 + financials[Month Number], "@v", [Total Sales] )
			VAR _xmin = MINX ( _m, [@idx] )
			VAR _xmax = MAXX ( _m, [@idx] )
			VAR _ymin = MINX ( _m, [@v] )
			VAR _ymax = MAXX ( _m, [@v] )
			VAR _pts = CONCATENATEX ( _m, INT ( 100 * DIVIDE ( [@idx] - _xmin, _xmax - _xmin ) ) & "," & ( 30 - INT ( 30 * DIVIDE ( [@v] - _ymin, _ymax - _ymin ) ) ), " ", [@idx], ASC )
			RETURN
				IF ( HASONEVALUE ( financials[Product] ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 30'><polyline fill='none' stroke='#5B8DBE' stroke-width='2' points='" & _pts & "'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: ffe1761c-88d1-4215-a8b1-d61b8c0f39eb
		dataCategory: ImageUrl

	/// SVG bullet — Total Sales bar, target line, sentiment dot vs Product Target.
	measure 'Sales Bullet SVG' =
			VAR _Actual = [Total Sales]
			VAR _Target = [Product Target]
			VAR _Perf = DIVIDE ( _Actual - _Target, _Target )
			VAR _BarMax = 100
			VAR _BarMin = 20
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _Dot = SWITCH ( TRUE (), _Perf < -0.05, "#f4ae4c", _Perf < -0.025, "#ffe075", _Perf > 0.05, "#2D6390", _Perf > 0.025, "#74B2FF", "#FFFFFF00" )
			VAR _AxisMax = CALCULATE ( MAXX ( _Scope, [Total Sales] ), REMOVEFILTERS ( financials[Product] ) ) * 1.1
			VAR _Range = _BarMax - _BarMin
			VAR _AN = DIVIDE ( _Actual, _AxisMax ) * _Range
			VAR _TN = ( DIVIDE ( _Target, _AxisMax ) * _Range ) + _BarMin - 1
			RETURN
				IF ( HASONEVALUE ( financials[Product] ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'>" &
					"<circle cx='10' cy='11' r='5' fill='" & _Dot & "'/>" &
					"<rect x='" & _BarMin & "' y='2' width='" & _BarMax & "' height='80%' fill='#F5F5F5'/>" &
					"<rect x='" & _BarMin & "' y='5' width='" & _AN & "' height='50%' fill='#CFCFCF'/>" &
					"<rect x='" & _BarMin & "' y='4' width='1' height='60%' fill='#737373'/>" &
					"<rect x='" & _TN & "' y='2' width='2' height='80%' fill='#000000'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 9104b68e-d815-419c-9795-e11c82f1f2cc
		dataCategory: ImageUrl

	/// SVG dumbbell — Total Sales vs Product Target as connected dots.
	measure 'Sales Dumbbell SVG' =
			VAR _Actual = [Total Sales]
			VAR _Target = [Product Target]
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _AxisMax = CALCULATE ( MAXX ( _Scope, [Total Sales] ), REMOVEFILTERS ( financials[Product] ) ) * 1.1
			VAR _AN = DIVIDE ( _Actual, _AxisMax ) * 100
			VAR _TN = DIVIDE ( _Target, _AxisMax ) * 100
			VAR _Fill = IF ( _Actual > _Target, "#448FD6", "#D64444" )
			VAR _Stroke = IF ( _Actual > _Target, "#2F6698", "#982F2F" )
			RETURN
				IF ( HASONEVALUE ( financials[Product] ),
					"data:image/svg+xml;utf8,<svg width='100' height='25' xmlns='http://www.w3.org/2000/svg'>" &
					"<line x1='0' y1='12.5' x2='100' y2='12.5' stroke='#C7C7C7'/>" &
					"<line x1='" & _AN & "' y1='12.5' x2='" & _TN & "' y2='12.5' stroke='" & _Fill & "' stroke-width='3'/>" &
					"<circle cx='" & _TN & "' cy='12.5' r='4' fill='#F5F5F5' stroke='#C7C7C7' stroke-width='1.5'/>" &
					"<circle cx='" & _AN & "' cy='12.5' r='4' fill='" & _Fill & "' stroke='" & _Stroke & "' stroke-width='1.5'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 3fba2a89-3445-48a4-8bee-48fa3551e8fb
		dataCategory: ImageUrl

	/// SVG IBCS bar — AC (Total Sales, dark) vs PY (outlined), colored delta extension.
	measure 'Sales IBCS Bar SVG' =
			VAR _AC = [Total Sales]
			VAR _PY = [Sales PY]
			VAR _Delta = _AC - _PY
			VAR _BarMax = 110
			VAR _BarMin = 40
			VAR _H = 22
			VAR _BarH = 10
			VAR _BarY = ( _H - _BarH ) / 2
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _DeltaColor = IF ( _Delta >= 0, "#006600", "#CC0000" )
			VAR _MaxAC = CALCULATE ( MAXX ( _Scope, [Total Sales] ), REMOVEFILTERS ( financials[Product] ) )
			VAR _MaxPY = CALCULATE ( MAXX ( _Scope, [Sales PY] ), REMOVEFILTERS ( financials[Product] ) )
			VAR _AxisMax = MAX ( _MaxAC, _MaxPY ) * 1.1
			VAR _Range = _BarMax - _BarMin
			VAR _ACw = DIVIDE ( _AC, _AxisMax ) * _Range
			VAR _PYw = DIVIDE ( _PY, _AxisMax ) * _Range
			VAR _Dx = _BarMin + MIN ( _ACw, _PYw )
			VAR _Dw = ABS ( _ACw - _PYw )
			RETURN
				IF ( HASONEVALUE ( financials[Product] ) && NOT ISBLANK ( _PY ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 150 22'>" &
					"<rect x='" & _BarMin & "' y='" & ( _BarY - 1 ) & "' width='" & _PYw & "' height='" & ( _BarH + 2 ) & "' fill='none' stroke='#C6C6C6' stroke-width='1'/>" &
					"<rect x='" & _BarMin & "' y='" & _BarY & "' width='" & _ACw & "' height='" & _BarH & "' fill='#404040'/>" &
					"<rect x='" & _Dx & "' y='" & ( _BarY + 2 ) & "' width='" & _Dw & "' height='" & ( _BarH - 4 ) & "' fill='" & _DeltaColor & "'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 928e12da-f32b-4056-b3d3-3bf8175d893f
		dataCategory: ImageUrl

	/// SVG overlapping bars — Total Sales over Product Target with variance bar + label.
	measure 'Sales Overlapping Bars SVG' =
			VAR _Actual = [Total Sales]
			VAR _Target = [Product Target]
			VAR _Perf = DIVIDE ( _Actual - _Target, _Target )
			VAR _BarMax = 100
			VAR _BarMin = 30
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _VarColor = IF ( _Perf < 0, "#fab005", "#2094ff" )
			VAR _MaxA = CALCULATE ( MAXX ( _Scope, [Total Sales] ), REMOVEFILTERS ( financials[Product] ) )
			VAR _AxisMax = MAX ( _MaxA, _Target ) * 1.1
			VAR _Range = _BarMax - _BarMin
			VAR _AN = DIVIDE ( _Actual, _AxisMax ) * _Range
			VAR _TN = DIVIDE ( _Target, _AxisMax ) * _Range
			VAR _Vx = _BarMin + MIN ( _AN, _TN ) + 1
			VAR _Vy = IF ( _Target > _Actual, 2.9, 9 )
			VAR _Vw = ABS ( _AN - _TN ) - 1
			RETURN
				IF ( HASONEVALUE ( financials[Product] ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'>" &
					"<text x='" & ( _BarMin - 10 ) & "' y='15' font-family='Segoe UI' font-size='10' font-weight='600' text-anchor='end' fill='" & _VarColor & "'>" & FORMAT ( _Perf, "#,##0%;#,##0%;#,##0%" ) & "</text>" &
					"<rect x='" & _BarMin & "' y='10' width='" & _TN & "' height='12' stroke='#686868' fill='#e1dfdd'/>" &
					"<rect x='" & _BarMin & "' y='3' width='" & _AN & "' height='12' stroke='#686868' fill='#686868'/>" &
					"<rect x='" & _Vx & "' y='" & _Vy & "' width='" & _Vw & "' height='6' fill='" & _VarColor & "'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 4e86c82b-f310-42a0-8f8f-59cd3302ac46
		dataCategory: ImageUrl

	/// SVG lollipop — Total Sales bar+dot, conditional color vs Product Target.
	measure 'Sales Lollipop SVG' =
			VAR _Actual = [Total Sales]
			VAR _Target = [Product Target]
			VAR _Perf = DIVIDE ( _Actual - _Target, _Target )
			VAR _BarColor = SWITCH ( TRUE (), _Perf < 0, "#ffd43b", _Perf > 0, "#a5d8ff", "#CACACA" )
			VAR _LabelColor = SWITCH ( TRUE (), _Perf < 0, "#c68c03", _Perf > 0, "#1971c2", "#CACACA" )
			VAR _Num = SWITCH ( TRUE (), _Actual <= 1E3, FORMAT ( _Actual, "#,0." ), _Actual <= 1E6, FORMAT ( _Actual, "#,0,.0 K" ), _Actual <= 1E9, FORMAT ( _Actual, "#,0,,.0 M" ), FORMAT ( _Actual, "#,0,,,.0 bn" ) )
			VAR _BarMax = 95
			VAR _BarMin = 44
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _AxisMax = CALCULATE ( MAXX ( _Scope, [Total Sales] ), REMOVEFILTERS ( financials[Product] ) ) * 1.1
			VAR _Range = _BarMax - _BarMin
			VAR _AN = DIVIDE ( _Actual, _AxisMax ) * _Range
			RETURN
				IF ( HASONEVALUE ( financials[Product] ),
					"data:image/svg+xml;utf8, <svg xmlns='http://www.w3.org/2000/svg'>" &
					"<rect x='" & _BarMin & "' y='10' width='" & _AN & "' height='15%' fill='" & _BarColor & "'/>" &
					"<circle cx='" & ( _AN + _BarMin ) & "' cy='11.75' r='" & MAX ( DIVIDE ( _Actual, _AxisMax ) * 7.5, 3.5 ) & "' fill='" & _BarColor & "'/>" &
					"<text x='40' y='16' font-family='Segoe UI' font-size='11' font-weight='600' text-anchor='end' fill='" & _LabelColor & "'>" & _Num & "</text></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 1d8c3e55-46bb-4784-b67d-a74a9039a440
		dataCategory: ImageUrl

	/// SVG target bar (linear gauge) — Profit % with red/amber/green zones + needle.
	measure 'Profit Target Bar SVG' =
			VAR _ratio = [Profit %]
			VAR _pct = MIN ( MAX ( _ratio, 0 ), 1 ) * 100
			VAR _x0 = 10
			VAR _x1 = 300
			VAR _trackW = _x1 - _x0
			VAR _needleX = _x0 + _trackW * _pct / 100
			RETURN
				"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 60' font-family='Segoe UI, Arial, sans-serif'>" &
				"<rect x='" & _x0 & "' y='28' width='" & ( _trackW * 0.30 ) & "' height='10' fill='#f4d4d0'/>" &
				"<rect x='" & ( _x0 + _trackW * 0.30 ) & "' y='28' width='" & ( _trackW * 0.40 ) & "' height='10' fill='#f5e1c8'/>" &
				"<rect x='" & ( _x0 + _trackW * 0.70 ) & "' y='28' width='" & ( _trackW * 0.30 ) & "' height='10' fill='#d6e7d3'/>" &
				"<line x1='" & _x0 & "' y1='32' x2='" & _x1 & "' y2='32' stroke='#222' stroke-width='1'/>" &
				"<line x1='" & _needleX & "' y1='18' x2='" & _needleX & "' y2='42' stroke='#c97a3a' stroke-width='1.5'/>" &
				"<polygon points='" & _needleX & ",14 " & ( _needleX + 5 ) & ",19 " & _needleX & ",24 " & ( _needleX - 5 ) & ",19' fill='#c97a3a'/></svg>"
		displayFolder: 7. SVG gallery
		lineageTag: 548d07dc-163f-47aa-9303-2782b8fbb060
		dataCategory: ImageUrl

	/// SVG boxplot — distribution of Total Sales across products (per Segment row).
	measure 'Sales Boxplot SVG' =
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _Data = ADDCOLUMNS ( _Scope, "@Val", [Total Sales] )
			VAR _Q1 = PERCENTILEX.INC ( _Data, [@Val], 0.25 )
			VAR _Median = PERCENTILEX.INC ( _Data, [@Val], 0.5 )
			VAR _Q3 = PERCENTILEX.INC ( _Data, [@Val], 0.75 )
			VAR _IQR = _Q3 - _Q1
			VAR _Min = MINX ( _Data, [@Val] )
			VAR _Max = MAXX ( _Data, [@Val] )
			VAR _WLo = MAX ( _Min, _Q1 - 1.5 * _IQR )
			VAR _WHi = MIN ( _Max, _Q3 + 1.5 * _IQR )
			VAR _Range = _Max - _Min
			VAR _W = 96
			VAR _H = 22
			VAR _Pad = 2
			VAR _BoxH = _H * 0.5
			VAR _BoxY = ( _H - _BoxH ) / 2
			VAR _MidY = _H / 2
			VAR _Scale = DIVIDE ( _W - 2 * _Pad, _Range )
			VAR _Q1x = ( _Q1 - _Min ) * _Scale + _Pad
			VAR _Q3x = ( _Q3 - _Min ) * _Scale + _Pad
			VAR _Mx = ( _Median - _Min ) * _Scale + _Pad
			VAR _WLx = ( _WLo - _Min ) * _Scale + _Pad
			VAR _WHx = ( _WHi - _Min ) * _Scale + _Pad
			RETURN
				IF ( HASONEVALUE ( financials[Segment] ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 22'>" &
					"<line x1='" & _WLx & "' y1='" & _MidY & "' x2='" & _Q1x & "' y2='" & _MidY & "' stroke='#999999' stroke-width='1'/>" &
					"<line x1='" & _Q3x & "' y1='" & _MidY & "' x2='" & _WHx & "' y2='" & _MidY & "' stroke='#999999' stroke-width='1'/>" &
					"<rect x='" & _Q1x & "' y='" & _BoxY & "' width='" & ( _Q3x - _Q1x ) & "' height='" & _BoxH & "' fill='#E8F0FE' stroke='#448FD6' stroke-width='1.5'/>" &
					"<line x1='" & _Mx & "' y1='" & _BoxY & "' x2='" & _Mx & "' y2='" & ( _BoxY + _BoxH ) & "' stroke='#D64444' stroke-width='2'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 8023866d-aa97-43b4-8b38-857e6db12553
		dataCategory: ImageUrl

	/// SVG jitter plot — Total Sales dots across products with average line (per Segment row).
	measure 'Sales Jitter SVG' =
			VAR _Scope = ALLSELECTED ( financials[Product] )
			VAR _W = 96
			VAR _H = 22
			VAR _Pad = 4
			VAR _DotR = 2.5
			VAR _Data = ADDCOLUMNS ( _Scope, "@Val", [Total Sales], "@Idx", RANKX ( _Scope, [Total Sales], , ASC ) )
			VAR _Min = MINX ( _Data, [@Val] )
			VAR _Max = MAXX ( _Data, [@Val] )
			VAR _Avg = AVERAGEX ( _Data, [@Val] )
			VAR _Range = _Max - _Min
			VAR _Scale = DIVIDE ( _W - 2 * _Pad, _Range )
			VAR _AvgX = ( _Avg - _Min ) * _Scale + _Pad
			VAR _Dots = CONCATENATEX ( _Data, VAR _X = ( [@Val] - _Min ) * _Scale + _Pad VAR _Seed = ABS ( [@Val] * 12345 + [@Idx] * 67890 ) VAR _J = MOD ( _Seed, 10000 ) / 10000 VAR _Y = _Pad + _J * ( _H - 2 * _Pad ) RETURN "<circle cx='" & _X & "' cy='" & _Y & "' r='" & _DotR & "' fill='#448FD6' opacity='0.6'/>", "", [@Idx], ASC )
			RETURN
				IF ( HASONEVALUE ( financials[Segment] ),
					"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 22'>" & _Dots &
					"<line x1='" & _AvgX & "' y1='1' x2='" & _AvgX & "' y2='21' stroke='#D64444' stroke-width='1.5' stroke-dasharray='3,2'/></svg>" )
		displayFolder: 7. SVG gallery
		lineageTag: 5a07fbe1-7453-4ffb-a379-be3a3b06500b
		dataCategory: ImageUrl

	column _
		lineageTag: 664b670f-5eba-42a4-a1b0-bd68e0351e73
		isNameInferred
		sourceColumn: [_]

	partition _Measures = calculated
		mode: import
		source = ROW("_", "")

	annotation PBI_ResultType = Table

