table DimItem
	lineageTag: 62bccdc0-f04b-42b6-b09d-7518a29f9081

	column ItemKey
		dataType: int64
		lineageTag: 459d1e91-98b6-4868-952f-e91ed0700e33
		summarizeBy: none
		sourceColumn: ItemKey

	column ItemName
		dataType: string
		lineageTag: 09e73756-60c9-4543-80c4-ef70cf77c807
		summarizeBy: none
		sourceColumn: ItemName

	column ItemCategory
		dataType: string
		lineageTag: 1b5cfa40-b2a9-4b90-bcfe-ef77bad9a923
		summarizeBy: none
		sourceColumn: ItemCategory

	partition DimItem = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Workspace-Blueprint\synthetic-data\outputs\grand-exchange\latest\DimItem.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"ItemKey", Int64.Type}, {"ItemName", type text}, {"ItemCategory", type text}}),
				    Filtered = Table.SelectRows(Typed, each [ItemKey] <= 3),
				    Kept = Table.SelectColumns(Filtered, {"ItemKey", "ItemName", "ItemCategory"})
				in
				    Kept

