table DimAdventurer
	lineageTag: 18340131-b552-4a43-be52-2d3c48f1e587

	column AdventurerKey
		dataType: int64
		isHidden
		isKey
		lineageTag: 33e3bba8-24fc-4768-8747-8fbb66f13c9b
		summarizeBy: none
		sourceColumn: AdventurerKey

	column Adventurer
		dataType: string
		lineageTag: b4198278-4373-40a4-81c2-a1a81122e889
		summarizeBy: none
		sourceColumn: Adventurer

	column Rank
		dataType: string
		lineageTag: 1d413800-c307-4b1d-97e7-e4751a47ef50
		summarizeBy: none
		sourceColumn: Rank

	column Class
		dataType: string
		lineageTag: 73eec43f-b861-4c79-9816-6af5a757edc8
		summarizeBy: none
		sourceColumn: Class

	partition DimAdventurer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "DimAdventurer.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"AdventurerKey", Int64.Type}, {"Adventurer", type text}, {"Rank", type text}, {"Class", type text}})
				in
				    Typed

