table DimDate
	lineageTag: 9afe5b3e-0cd3-4f1c-be81-ddccc6b65954
	dataCategory: Time

	column Date
		dataType: dateTime
		isUnique
		formatString: dd mmm yyyy
		lineageTag: 280460b4-c1a6-46df-89eb-49292f686966
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		isHidden
		isKey
		lineageTag: e0e41125-f99f-4b03-89aa-091d9e49e38c
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d0a78c2f-efd3-4fef-b731-667de3177f6e
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5f46bc57-29ed-4989-8dab-a0ce1fb69b26
		summarizeBy: none
		sourceColumn: Quarter

	column Month
		dataType: int64
		isHidden
		lineageTag: 59ff80ae-49b1-4c58-a10d-216b538cf14c
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d0d74b46-a840-490e-a591-a9a6ac63b6ee
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

	column DayName
		dataType: string
		lineageTag: ab0e4f5d-c684-4930-a411-40cf48243196
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayNum

	column DayNum
		dataType: int64
		isHidden
		lineageTag: d4e6de6e-5092-4ab3-8b66-f8eb7864c5bf
		summarizeBy: sum
		sourceColumn: DayNum

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: int64
		isHidden
		lineageTag: ad9e4c00-42cb-4123-8092-a488f46dfbf6
		summarizeBy: sum
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column MonthYear
		dataType: string
		lineageTag: 42f01354-ff93-46b4-88b5-f8525cd15920
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: YearMonth

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "DimDate.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Date", type date}, {"DateKey", Int64.Type}, {"Year", Int64.Type}, {"Quarter", type text}, {"Month", Int64.Type}, {"MonthName", type text}, {"DayName", type text}, {"DayNum", Int64.Type}, {"YearMonth", Int64.Type}, {"MonthYear", type text}})
				in
				    Typed

