table DimQuestType
	lineageTag: 2f87e96d-f927-4397-b099-01088b7ff299

	column QuestTypeKey
		dataType: int64
		isHidden
		isKey
		lineageTag: 6a50bd05-5c67-4143-866a-51ca431caae9
		summarizeBy: count
		sourceColumn: QuestTypeKey

		annotation SummarizationSetBy = Automatic

	column QuestType
		dataType: string
		lineageTag: 25ffc073-76ed-4945-b98c-c97e6a9a0725
		summarizeBy: none
		sourceColumn: QuestType

	column Danger
		dataType: string
		lineageTag: e2445b28-3cf1-46c5-aac4-507d1c01687d
		summarizeBy: none
		sourceColumn: Danger

	partition DimQuestType = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "DimQuestType.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"QuestTypeKey", Int64.Type}, {"QuestType", type text}, {"Danger", type text}})
				in
				    Typed

