table FactQuests
	lineageTag: 664d8acb-b137-4b71-b1db-35cbcafa6f1a

	column QuestsKey
		dataType: int64
		isHidden
		isKey
		lineageTag: 6491daa9-31ea-424e-8e1e-dc6752bae80c
		summarizeBy: count
		sourceColumn: QuestsKey

		annotation SummarizationSetBy = Automatic

	column Bounty
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: f47c2afe-e1ae-44a1-b8a9-02e1949ddbe9
		summarizeBy: sum
		sourceColumn: Bounty

	column DaysOnQuest
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: e714752b-9373-4a70-adb3-c287b0dd5506
		summarizeBy: sum
		sourceColumn: DaysOnQuest

	column DateKey
		dataType: int64
		isHidden
		lineageTag: 7a305d7a-4310-44c3-afa7-eaed7b0d77c7
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column GuildHallKey
		dataType: int64
		isHidden
		lineageTag: 367a8bb6-0f0c-4306-b386-c63840076bff
		summarizeBy: count
		sourceColumn: GuildHallKey

		annotation SummarizationSetBy = Automatic

	column QuestTypeKey
		dataType: int64
		isHidden
		lineageTag: 6cba08cd-7409-4cd0-a450-ca197fbb0555
		summarizeBy: count
		sourceColumn: QuestTypeKey

		annotation SummarizationSetBy = Automatic

	column AdventurerKey
		dataType: int64
		isHidden
		lineageTag: 43ae30b4-b9a9-439a-b751-42214193edde
		summarizeBy: count
		sourceColumn: AdventurerKey

		annotation SummarizationSetBy = Automatic

	partition FactQuests = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "FactQuests.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"QuestsKey", Int64.Type}, {"Bounty", type number}, {"DaysOnQuest", type number}, {"DateKey", Int64.Type}, {"GuildHallKey", Int64.Type}, {"QuestTypeKey", Int64.Type}, {"AdventurerKey", Int64.Type}}),
				    Rounded = Table.TransformColumns(Typed, {{"Bounty", each Number.Round(_, 2), type number}, {"DaysOnQuest", each Number.Round(_, 2), type number}})
				in
				    Rounded

