table FactMarketPriceDaily
	lineageTag: 15ec165b-e4a4-4be0-b7dc-7c78d6efc8a6

	column DateKey
		dataType: int64
		lineageTag: 8809dd56-ba38-4209-8c09-2101266338ef
		summarizeBy: none
		sourceColumn: DateKey

	column ItemKey
		dataType: int64
		lineageTag: 194c6721-d197-4650-9184-4971ea35d5c3
		summarizeBy: none
		sourceColumn: ItemKey

	column OpenPrice
		dataType: double
		lineageTag: abcaa8c9-c932-4a8c-ad5e-ce8b16fc26dc
		summarizeBy: none
		sourceColumn: OpenPrice

	column ClosePrice
		dataType: double
		lineageTag: c64fa81a-9ead-4f37-96a7-4fde2594b5bc
		summarizeBy: none
		sourceColumn: ClosePrice

	column HighPrice
		dataType: double
		lineageTag: 629e80a5-6e97-4230-97c8-ad804ab2fefe
		summarizeBy: none
		sourceColumn: HighPrice

	column LowPrice
		dataType: double
		lineageTag: 599bc07b-fb21-4ef7-9833-1d2b8a805e0f
		summarizeBy: none
		sourceColumn: LowPrice

	column AvgPrice
		dataType: double
		lineageTag: ac1f794f-6d0d-4e20-ba52-e8289da4fba3
		summarizeBy: none
		sourceColumn: AvgPrice

	column Volume
		dataType: int64
		lineageTag: 620f10bf-2f39-41f5-9a45-110722ad92c5
		summarizeBy: none
		sourceColumn: Volume

	column ListingsCount
		dataType: int64
		lineageTag: 2781005d-b664-4ebf-902d-b05f2b0a8f6d
		summarizeBy: none
		sourceColumn: ListingsCount

	partition FactMarketPriceDaily = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Workspace-Blueprint\synthetic-data\outputs\grand-exchange\latest\FactMarketPriceDaily.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"DateKey", Int64.Type}, {"ItemKey", Int64.Type}, {"OpenPrice", type number}, {"ClosePrice", type number}, {"HighPrice", type number}, {"LowPrice", type number}, {"AvgPrice", type number}, {"Volume", Int64.Type}, {"ListingsCount", Int64.Type}}),
				    Filtered = Table.SelectRows(Typed, each [ItemKey] <= 3 and [DateKey] >= 20260101)
				in
				    Filtered

