/// 24 items in five categories. Config list order is the pareto rank - flagships first.
table DimItem
	lineageTag: 3a52da73-c725-48f7-a694-0068ad8de468

	column ItemKey
		dataType: int64
		isHidden
		isKey
		lineageTag: ecef2e59-be93-4334-8db9-638645f759ed
		summarizeBy: none
		sourceColumn: ItemKey

	column Item
		dataType: string
		lineageTag: efa20f9f-c753-483b-9918-95f87c736b17
		summarizeBy: none
		sourceColumn: Item

	column Category
		dataType: string
		lineageTag: e86a752d-3f85-4492-acb4-37cdae7f8e60
		summarizeBy: none
		sourceColumn: Category

	partition DimItem = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(SourceFolder & "DimItem.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"ItemKey", Int64.Type}, {"Item", type text}, {"Category", type text}})
				in
				    Typed

